[toolchain]
channel = "stable"
targets = [
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",

    # wasm
    "wasm32-unknown-unknown",
]
components = ["clippy", "rustfmt"]